//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMat.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eMatriculaEntities : DbContext
    {
        public eMatriculaEntities()
            : base("name=eMatriculaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbCarrera> tbCarrera { get; set; }
        public DbSet<tbCurso> tbCurso { get; set; }
        public DbSet<tbEstudiante> tbEstudiante { get; set; }
        public DbSet<tbGrupo> tbGrupo { get; set; }
        public DbSet<tbMatricula> tbMatricula { get; set; }
        public DbSet<tbPlanEstudio> tbPlanEstudio { get; set; }
    }
}
