//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMat.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCarrera
    {
        public tbCarrera()
        {
            this.tbEstudiante = new HashSet<tbEstudiante>();
        }
    
        public string sigla { get; set; }
        public string carrera { get; set; }
    
        public virtual tbPlanEstudio tbPlanEstudio { get; set; }
        public virtual ICollection<tbEstudiante> tbEstudiante { get; set; }
    }
}
