//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMat.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCarrera
    {
        public tbCarrera()
        {
            this.tbEstudiante = new HashSet<tbEstudiante>();
        }
    
        public string sigla { get; set; }
        public string carrera { get; set; }
    
        public virtual tbPlanEstudio tbPlanEstudio { get; set; }
        public virtual ICollection<tbEstudiante> tbEstudiante { get; set; }
    }
}
