//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMat.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCurso
    {
        public tbCurso()
        {
            this.tbGrupo = new HashSet<tbGrupo>();
            this.tbPlanEstudio = new HashSet<tbPlanEstudio>();
            this.tbCurso1 = new HashSet<tbCurso>();
            this.tbCurso2 = new HashSet<tbCurso>();
        }
    
        public string idCurso { get; set; }
        public string nombre { get; set; }
        public int creditos { get; set; }
    
        public virtual ICollection<tbGrupo> tbGrupo { get; set; }
        public virtual ICollection<tbPlanEstudio> tbPlanEstudio { get; set; }
        public virtual ICollection<tbCurso> tbCurso1 { get; set; }
        public virtual ICollection<tbCurso> tbCurso2 { get; set; }
    }
}
