//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMat.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCurso
    {
        public tbCurso()
        {
            this.tbGrupo = new HashSet<tbGrupo>();
            this.tbPlanEstudio = new HashSet<tbPlanEstudio>();
            this.tbCurso1 = new HashSet<tbCurso>();
            this.tbCurso2 = new HashSet<tbCurso>();
        }
    
        public string idCurso { get; set; }
        public string nombre { get; set; }
        public int creditos { get; set; }
    
        public virtual ICollection<tbGrupo> tbGrupo { get; set; }
        public virtual ICollection<tbPlanEstudio> tbPlanEstudio { get; set; }
        public virtual ICollection<tbCurso> tbCurso1 { get; set; }
        public virtual ICollection<tbCurso> tbCurso2 { get; set; }
    }
}
