//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMat.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGrupo
    {
        public tbGrupo()
        {
            this.tbMatricula = new HashSet<tbMatricula>();
        }
    
        public int idGrupo { get; set; }
        public string idCurso { get; set; }
        public int horario { get; set; }
    
        public virtual tbCurso tbCurso { get; set; }
        public virtual ICollection<tbMatricula> tbMatricula { get; set; }
    }
}
