//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMat.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGrupo
    {
        public tbGrupo()
        {
            this.tbMatricula = new HashSet<tbMatricula>();
        }
    
        public int idGrupo { get; set; }
        public string idCurso { get; set; }
        public int horario { get; set; }
    
        public virtual tbCurso tbCurso { get; set; }
        public virtual ICollection<tbMatricula> tbMatricula { get; set; }
    }
}
