//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMat.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMatricula
    {
        public int carnet { get; set; }
        public int idGrupo { get; set; }
        public int cuatrimestre { get; set; }
        public int anio { get; set; }
        public string nota { get; set; }
    
        public virtual tbEstudiante tbEstudiante { get; set; }
        public virtual tbGrupo tbGrupo { get; set; }
    }
}
