//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMat.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPlanEstudio
    {
        public tbPlanEstudio()
        {
            this.tbCurso = new HashSet<tbCurso>();
        }
    
        public string sigla { get; set; }
        public string nombre { get; set; }
    
        public virtual tbCarrera tbCarrera { get; set; }
        public virtual ICollection<tbCurso> tbCurso { get; set; }
    }
}
