//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eMat.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPlanEstudio
    {
        public tbPlanEstudio()
        {
            this.tbCurso = new HashSet<tbCurso>();
        }
    
        public string sigla { get; set; }
        public string nombre { get; set; }
    
        public virtual tbCarrera tbCarrera { get; set; }
        public virtual ICollection<tbCurso> tbCurso { get; set; }
    }
}
