//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uantillas.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCarrera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCarrera()
        {
            this.tbEstudiante = new HashSet<tbEstudiante>();
        }
    
        public string sigla { get; set; }
        public string carrera { get; set; }
    
        public virtual tbPlanEstudio tbPlanEstudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEstudiante> tbEstudiante { get; set; }
    }
}
