//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uantillas.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPlanEstudio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPlanEstudio()
        {
            this.tbCurso = new HashSet<tbCurso>();
        }
    
        public string sigla { get; set; }
        public string nombre { get; set; }
    
        public virtual tbCarrera tbCarrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCurso> tbCurso { get; set; }
    }
}
